<a href="https://colab.research.google.com/github/pramchan/OpenTech/blob/master/Copy_of_nppd_tf_crash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as dp

In [ ]:
# Creating lists
list_1 = [1, 2, 3]

list_2 = [5, 6, 4]

# Adding two lists
list_1 + list_2


[1, 2, 3, 5, 6, 4]

In [ ]:
# Creating arrays
arr_1 = np.array([1, 2, 3])

arr_2 = np.array([5, 6, 4])

# Adding two arrays
arr_1 + arr_2


array([6, 8, 7])

In [ ]:
# Creating a one-dimensional array
zarray = np.zeros(5)
print (np.zeros(5))
print (zarray)
# Creating a two-dimensional array (note default is dtype float 0. & not 0)
np.zeros((3, 5))

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Creating a one-dimensional array of integer type
array_int=np.zeros(5, dtype=int)
print (array_int)
# Creating a one-dimensional array of float type
array_float=np.zeros(5, dtype=float)
print(array_float)


[0 0 0 0 0]
[0. 0. 0. 0. 0.]


In [ ]:
# Creating a one-dimensional array of integer type
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [ ]:
 #full(shape, fill_value, dtype=None) returns an array of a given shape and type, fill with fill_value given in input parameters.

# Creating a one-dimensional array with value as 12
np.full(5, 12)
np.full((3,4), 1.0)



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Creating a one-dimensional array with value as 12
print (np.full(5, 12))
# Creating a two-dimensional array with value as 9
print (np.full((2, 3), 9))

[12 12 12 12 12]
[[9 9 9]
 [9 9 9]]


In [ ]:
# Creating an array with only stop argument
print (np.arange(5))
# Creating an array with start and stop arguments
print(np.arange(3, 8))

[0 1 2 3 4]
[3 4 5 6 7]


In [ ]:
# Creating an array with given interval and step value as 0.5
np.arange(3, 8, 0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

In [ ]:
# linspace(start, stop, num=50, endpoint=True)
# Creating an evenly spaced array with five numbers within interval 2 to 3
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
# Creating an array excluding end value
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
# Creating an array with ten values within the specified interval
np.linspace(11, 20, num=10)


array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [ ]:
# rand([d0, d1, ..., dn]) is used to create an array of a given shape 
# and populate it with random samples from a uniform distribution over [0, 1). 
# It takes only positive arguments. If no argument is provided, a single float value is returned.
# Generating single random number
np.random.rand()
                                                                                                                                             

array([0.64132635, 0.54954652, 0.43500752, 0.8382374 ])

In [ ]:
# Generating a one-dimensional array with four random values
np.random.rand(4)


array([0.4623245 , 0.34476778, 0.48485773, 0.2449246 ])

In [ ]:
# Generating a two-dimensional array
np.random.rand(2, 3)

array([[0.35248655, 0.7673033 , 0.1563021 ],
       [0.20753569, 0.98208059, 0.30346319]])